<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>com.io7m.jade</artifactId>
    <groupId>com.io7m.jade</groupId>
    <version>1.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>com.io7m.jade.bom</artifactId>

  <name>com.io7m.jade.bom</name>
  <description>Java application directory etiquette (BOM)</description>
  <url>https://www.io7m.com/software/jade</url>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>com.io7m.jade.api</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>com.io7m.jade.vanilla</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>com.io7m.jade.spi</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>